project2/library/urls.py
from django.urls import path

from . import views

app_name = 'lib'

urlpatterns = [
    path('', view=views.index, name='index'),
    path('book/all/', view=views.book_list, name='book-list'),
    path('book/<int:pk>/', view=views.book_detail, name='book-detail'),
    path('author/all/', view=views.author_list, name='author-list'),
    path('author/<int:pk>/', view=views.author_detail, name='author-detail'),
    path('genre/all/', view=views.genre_list, name='genre-list'),
    path('book/comment/<int:pk>/', view=views.add_comment, name='add-comment')
]

project2/project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('library.urls')),
]

project2/library/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

class Genre(models.Model):
    name = models.CharField(max_length=128)
    # books

    def __str__(self):
        return self.name

    def url(self):
        return reverse('lib:genre-list') + f'#g-{self.id}'



class Author(models.Model):
    first = models.CharField(max_length=128)
    last = models.CharField(max_length=128)
    birth_date = models.DateField(null=True, blank=True)
    portrait = models.URLField(null=True, blank=True)
    # books

    def __str__(self):
        return f'{self.first} {self.last}'

    def url(self):
        return reverse('lib:author-detail', kwargs={'pk': self.id})

    def genres(self):
        # genre_list = []
        # for book in self.books.all():
        #     for genre in book.genres.all():
        #         if genre not in genre_list:
        #             genre_list.append(genre)
        genre_list = Genre.objects.filter(books__author__exact=self).distinct()
        return genre_list

    def comments(self):
        return Comment.objects.filter(book__author__exact=self)


class Book(models.Model):
    title = models.CharField(max_length=512)
    cover = models.URLField(null=True, blank=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='books')
    genres = models.ManyToManyField(Genre, related_name='books', blank=True)
    # comments
    # instances

    def __str__(self):
        return f'"{self.title}"'

    def url(self):
        return reverse('lib:book-detail', kwargs={'pk': self.id})


class Comment(models.Model):
    text = models.TextField()
    author = models.CharField(max_length=128)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments')
    published = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-published']


class BookInstance(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='instances')
    LOAN_STATUSES = (
        ('a', 'available'),
        ('o', 'on loan'),
        ('m', 'maintenance'),
        ('r', 'reserved'),
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUSES,
                              default='a')

    due_back = models.DateField(null=True, blank=True)


    # def __str__(self):
    #     return f'"{self.title}"'

project2/library/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import *


def index(request):
    context = {
        'books_number': len(Book.objects.all()),
        'authors_number': len(Author.objects.all()),
        'genres_number': len(Genre.objects.all()),
    }
    return render(request, template_name='library/index.html', context=context)


def book_list(request):
    context = {
        'books': Book.objects.order_by('title'),
    }
    return render(request, template_name='library/book_list.html', context=context)


def book_detail(request, pk):
    context = {
        'book': Book.objects.get(pk=pk),
    }
    return render(request, template_name='library/book_detail.html', context=context)


def author_list(request):
    context = {
        'authors': Author.objects.order_by('last', 'first'),
    }
    return render(request, template_name='library/author_list.html', context=context)


def author_detail(request, pk):
    context = {
        'author': Author.objects.get(id__exact=pk),
    }
    return render(request, template_name='library/author_detail.html', context=context)


def genre_list(request):
    context = {
        'genres': Genre.objects.order_by('name'),
    }
    return render(request, template_name='library/genre_list.html', context=context)


def add_comment(request, pk):
    text = request.POST.get('text')
    author = request.POST.get('author')
    book = get_object_or_404(Book, id=pk)
    if text and author:
        new_comment = Comment(text=text, author=author, book=book)
        new_comment.save()
    return HttpResponseRedirect(book.url())

project2/library/templates/library/author_detail.html
{% extends "library/base.html" %} {% load static %} {% block title %} {{ author
}} {% endblock %} {% block content %}

<h1 class="text-center my-3 text-success">{{ author }}</h1>

<div class="row justify-content-around mt-4">
  <div class="col-3">
    {% for genre in author.genres %}
    <a href="{{ genre.url }}" class="text-secondary text-decoration-none"
      >{{ genre }}</a
    >
    {% endfor %}
    <img src="{{ author.portrait }}" class="img-fluid" />
    <p>Born: {{ author.birth_date }}</p>
  </div>
  <div class="col-4">
    {% for book in author.books.all %}
    <div class="row my-2">
      <div class="col-2">
        <img src="{{ book.cover }}" class="img-fluid" />
      </div>
      <div class="col-8">
        <a href="{{ book.url }}" class="text-decoration-none"
          ><h4 class="text-primary">{{ book }}</h4></a
        >
      </div>
    </div>
    {% endfor %}

    <h3>Comments:</h3>
    {% for comment in author.comments.all %}
    <p>
      <i>
        {{ comment.author }} about
        <a href="{{ comment.book.url }}" class="text-decoration-none"
          >{{ comment.book }}</a
        ></i
      ><br />{{ comment.text }} ({{ comment.published|timesince }})
    </p>
    {% empty %}
    <p>no comments yet</p>
    {% endfor %}
  </div>
</div>

{% endblock %}

project2/library/templates/library/author_list.html
{% extends "library/base.html" %} {% load static %} {% block title %} All
Authors {% endblock %} {% block content %}

<h1 class="text-center my-3">All Authors</h1>

<div class="row justify-content-around mt-4">
  {% for author in authors %}
  <div class="col-3 text-center bg-light m-3 p-3">
    <img src="{{ author.portrait }}" class="w-50 h-75" />
    <a href="{{ author.url }}" class="text-decoration-none"
      ><h5 class="text-success">{{ author }}</h5></a
    >
    <p>books: {{ author.books.all|length }}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

project2/library/templates/library/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
      crossorigin="anonymous"
    />
    <link
      rel="shortcut icon"
      href="{% static 'library/img/logo.png' %}"
      type="image/x-icon"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-1">
          <a href="{% url 'lib:index' %}"
            ><img src="{% static 'library/img/logo.png' %}" class="w-100"
          /></a>
        </div>
      </div>
{% block content %}
    
{% endblock %}
      </div>
    </div>
  </body>
</html>

project2/library/templates/library/book_detail.html
{% extends "library/base.html" %} {% load static %} {% block title %} {{ book }}
{% endblock %} {% block content %}

<h1 class="text-center my-3 text-primary">{{ book }}</h1>

<div class="row justify-content-around mt-4">
  <div class="col-3">
    {% for genre in book.genres.all %}
    <a href="{{ genre.url }}" class="text-secondary text-decoration-none"
      >{{ genre }}</a
    >
    {% endfor %}
    <img src="{{ book.cover }}" class="img-fluid mb-5" />

    <h3>Instances:</h3>
    {% for bi in book.instances.all %} {% if bi.status == 'a' %} 
    <p>instance id:{{ bi.id }} - {{ bi.get_status_display }}
    <button class="btn btn-success">order</button>
    {% endif %} 
    {% if bi.status == 'o' %} 
    <p>instance id:{{ bi.id }} - {{ bi.get_status_display }} (due back: {{ bi.due_back }})
    {% endif %}
    {% endfor %}</p> 
  </div>
  <div class="col-4">
    <img src="{{ book.author.portrait }}" width="75" />
    <a href="{{ book.author.url }}" class="text-decoration-none"
      ><h3 class="text-success">{{ book.author }}</h3></a
    >
    <h3>Comments:</h3>
    {% for c in book.comments.all %}

    <p>
      <small
        >{{ c.text }} <br />
        <i
          >(author: {{ c.author }}, {{ c.published|date:"Y-M-d" }} {{
          c.published|time:"H:i" }})</i
        ></small
      >
    </p>
    {% empty %}
    <p>no comments yet, leave first</p>

    {% endfor %}
    <form action="{% url 'lib:add-comment' book.id %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label class="form-label">Comment</label>
        <input
          type="text"
          class="form-control"
          placeholder="Your text"
          name="text"
        />
      </div>
      <div class="mb-3">
        <label class="form-label">Author</label>
        <input
          type="text"
          class="form-control"
          placeholder="Your name"
          name="author"
        />
      </div>
      <input type="submit" value="Add Comment" class="btn btn-primary" />
    </form>
  </div>
</div>

{% endblock %}

project2/library/templates/library/book_list.html
{% extends "library/base.html" %} {% load static %} {% block title %} All Books
{% endblock %} {% block content %}

<h1 class="text-center my-3">All Books</h1>

<div class="row justify-content-around mt-4">
  {% for book in books %}
  <div class="col-3 text-center bg-light m-3 p-3">
    <img src="{{ book.cover }}" class="w-50 h-75" />
    <a href="{{ book.url }}" class="text-decoration-none"
      ><h4 class="text-primary">{{ book }}</h4></a
    >
    <a href="{{ book.author.url }}" class="text-decoration-none"
      ><h5 class="text-success">{{ book.author }}</h5></a
    >
  </div>
  {% endfor %}
</div>
{% endblock %}

project2/library/templates/library/genre_list.html
{% extends "library/base.html" %} {% load static %} {% block title %} All Genres
{% endblock %} {% block content %}

<h1 class="text-center my-3">All Genres</h1>

{% for genre in genres %}
<h3 class="text-secondary" id="g-{{ genre.id }}">
  {{ genre }} (books: {{ genre.books.all|length }})
</h3>
<div class="row justify-content-start mt-4">
  {% for book in genre.books.all %}
  <div class="col-2 text-center bg-light m-3 p-3">
    <img src="{{ book.cover }}" class="w-50 h-75" />
    <a href="{{ book.url }}" class="text-decoration-none"
      ><p class="text-primary">{{ book }}</p></a
    >
    <a href="{{ book.author.url }}" class="text-decoration-none"
      ><small class="text-success">{{ book.author }}</small></a
    >
  </div>
  {% endfor %}
</div>
{% endfor %} {% endblock %}

project2/library/templates/library/index.html
{% extends "library/base.html" %}
{% load static %}

{% block title %}
  Powercode Library
{% endblock title %}

{% block content %}
        <h1 class="text-center">Powercode Library</h1>
      <div class="row justify-content-around mt-4">
        <div class="col-3 text-center border border-primary p-5">
          <a href="{% url 'lib:book-list' %}" class="text-decoration-none">
            <img
              src="{% static 'library/img/book.png' %}"
              class="w-50 h-50 m-3"
            />
            <h3>Books: {{ books_number }}</h3></a
          >
        </div>
        <div class="col-3 text-center border border-primary p-5">
          <a href="{% url 'lib:author-list' %}" class="text-decoration-none">
            <img
              src="{% static 'library/img/writer.png' %}"
              class="w-50 h-50 m-3"
            />
            <h3>Authors: {{ authors_number }}</h3></a
          >
        </div>
        <div class="col-3 text-center border border-primary p-5">
          <a href="{% url 'lib:genre-list' %}" class="text-decoration-none">
            <img
              src="{% static 'library/img/genre.png' %}"
              class="w-50 h-50 m-3"
            />
            <h3>Genres: {{ genres_number }}</h3></a
          >
        </div>
      </div>
{% endblock %}
  </body>
</html>